from __future__ import annotations

import argparse
import sys

import pandas as pd

from umutextstats.cli.command import CommandSpec
from umutextstats.io.feature_reader import FeatureReader
from umutextstats.output import write_output
from umutextstats.summary.aggregate import aggregate_features


def add_aggregate_arguments(
    parser: argparse.ArgumentParser,
) -> None:
    parser.add_argument(
        "features",
        help=(
            "Features CSV or structured JSONL generated by "
            "UMUTextStats, or '-' for stdin"
        ),
    )

    parser.add_argument(
        "--metadata",
        required=True,
        help=(
            "Original CSV dataset containing grouping columns, "
            "or '-' for stdin"
        ),
    )

    parser.add_argument(
        "--group-by",
        required=True,
        help="Metadata column used for grouping",
    )

    parser.add_argument(
        "--id-column",
        default="id",
        help="Shared identifier column",
    )

    parser.add_argument(
        "-o",
        "--output",
        default=None,
        help=(
            "Output aggregate file. "
            "If omitted, prints JSON to stdout."
        ),
    )


def run_aggregate(
    args: argparse.Namespace,
) -> None:
    if (
        args.features == "-"
        and args.metadata == "-"
    ):
        raise ValueError(
            "Features and metadata cannot both "
            "be read from stdin."
        )

    feature_reader = FeatureReader()

    feature_source = (
        sys.stdin
        if args.features == "-"
        else args.features
    )

    features = feature_reader.read(
        feature_source
    )

    if args.metadata == "-":
        metadata = pd.read_csv(
            sys.stdin
        )
    else:
        metadata = pd.read_csv(
            args.metadata
        )

    if args.id_column not in features.columns:
        raise ValueError(
            f"ID column '{args.id_column}' "
            "not found in features file."
        )

    if args.id_column not in metadata.columns:
        raise ValueError(
            f"ID column '{args.id_column}' "
            "not found in metadata file."
        )

    if args.group_by not in metadata.columns:
        available = ", ".join(
            metadata.columns
        )

        raise ValueError(
            f"Group column '{args.group_by}' "
            "not found in metadata file. "
            f"Available columns: {available}"
        )

    merged = features.merge(
        metadata[
            [
                args.id_column,
                args.group_by,
            ]
        ],
        on=args.id_column,
        how="left",
    )

    aggregate = aggregate_features(
        merged,
        group_by=args.group_by,
        exclude={
            args.id_column,
            args.group_by,
        },
    )

    if args.output:
        write_output(
            aggregate,
            args.output,
        )
    else:
        print(
            aggregate.to_json(
                orient="records",
                indent=2,
            )
        )


COMMAND = CommandSpec(
    name="aggregate",
    help="Compute grouped statistics",
    add_arguments=add_aggregate_arguments,
    run=run_aggregate,
)