from __future__ import annotations

import argparse
import json
from dataclasses import asdict
from pathlib import Path

from umutextstats.cli.command import CommandSpec
from umutextstats.evidence.service import (
    aggregate_dimension_from_jsonl,
)


def add_position_arguments(
    parser: argparse.ArgumentParser,
) -> None:
    parser.add_argument(
        "input",
        help=(
            "Structured JSONL file generated by "
            "UMUTextStats analyze or extract"
        ),
    )

    parser.add_argument(
        "dimension",
        help=(
            "Dimension key whose evidence will be "
            "distributed positionally"
        ),
    )

    parser.add_argument(
        "--segments",
        type=int,
        default=3,
        help=(
            "Number of equal-width positional segments. "
            "Default: 3"
        ),
    )

    parser.add_argument(
        "-o",
        "--output",
        default=None,
        help=(
            "Output JSON file. "
            "If omitted, prints JSON to stdout."
        ),
    )


def run_position(
    args: argparse.Namespace,
) -> None:
    result = aggregate_dimension_from_jsonl(
        path=args.input,
        dimension_key=args.dimension,
        segments=args.segments,
    )

    payload = asdict(
        result
    )

    serialized = json.dumps(
        payload,
        ensure_ascii=False,
        indent=2,
    )

    if args.output:
        output_path = Path(
            args.output
        )

        output_path.write_text(
            serialized + "\n",
            encoding="utf-8",
        )
    else:
        print(
            serialized
        )


COMMAND = CommandSpec(
    name="position",
    help=(
        "Aggregate the positional distribution "
        "of dimension evidence"
    ),
    add_arguments=add_position_arguments,
    run=run_position,
)